services:
  redis:
      image: redis:latest
      ports:
        - "6379:6379"

  app:
    build: ./app
    environment:
      - DATABASE_PATH=./database.db
    ports:
      - "5123:5123"

  worker:
    build: ./app
    depends_on:
      - redis
    environment:
      - DATABASE_PATH=./database.db
      - BROKER_URL=redis://redis:6379/0
    command: ["celery", "-A", "celery", "worker", "--loglevel=info"]

  beat:
    build: ./app
    depends_on:
      - redis
    environment:
      - DATABASE_PATH=./database.db
      - BROKER_URL=redis://redis:6379/0
    command: ["celery", "-A", "celery", "beat",  "--loglevel=info"]

