services:
  redis:
      image: redis:latest
      ports:
        - "6379:6379"

  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
    environment:
      - DATABASE_PATH=./database.db
    ports:
      - "5123:5123"
    volumes:
      - .:/app

  worker:
    build:
      context: ./app/
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - DATABASE_PATH=./database.db
      - BROKER_URL=redis://redis:6379/0
    command: ["celery", "-A", "celery", "worker", "--loglevel=info"]
    volumes:
      - .:/app
  
  beat:
    build:
      context: ./app/
      dockerfile: Dockerfile
    environment:
      - DATABASE_PATH=./database.db
    command: ["celery", "-A", "celery", "beat",  "--loglevel=info"]
    volumes:
      - .:/app
