services:
  redis:
      image: redis:latest

  app:
    container_name: book-looker
    build: ./app
    environment:
      - DATABASE_PATH=./database.db
    ports:
      - "5123:5123"

  worker:
    container_name: book-looker-worker
    build: ./app
    depends_on:
      - redis
    environment:
      - DATABASE_PATH=./database.db
      - BROKER_URL=redis://redis:6379/0
    command: ["celery", "-A", "celery", "worker", "--loglevel=info"]

  beat:
    container_name: book-looker-beat
    build: ./app
    depends_on:
      - redis
    environment:
      - DATABASE_PATH=./database.db
      - BROKER_URL=redis://redis:6379/0
    command: ["celery", "-A", "celery", "beat",  "--loglevel=info"]

